Traceback (most recent call last):
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env2/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env2/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env2/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env2/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env2/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env2/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env2/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from alignn.ff.ff import AlignnAtomwiseCalculator,default_path

model_path = default_path()
calc = AlignnAtomwiseCalculator(path=model_path)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01malignn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mff[39;00m[38;5;21;01m.[39;00m[38;5;21;01mff[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m AlignnAtomwiseCalculator,default_path
[1;32m      3[0m model_path [38;5;241m=[39m default_path()
[1;32m      4[0m calc [38;5;241m=[39m AlignnAtomwiseCalculator(path[38;5;241m=[39mmodel_path)

[0;31mModuleNotFoundError[0m: No module named 'alignn'

