Traceback (most recent call last):
  File "/home/colin/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/colin/.local/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/colin/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/colin/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/colin/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/colin/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ase.build import mx2
from ase.io import write
from ase.visualize import view # 3D interactive image

# This forms a primitive unit cell
Ti2C = mx2('CTi2', vacuum = 15)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[7], line 6[0m
[1;32m      3[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mase[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvisualize[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m view [38;5;66;03m# 3D interactive image[39;00m
[1;32m      5[0m [38;5;66;03m# This forms a primitive unit cell[39;00m
[0;32m----> 6[0m Ti2C [38;5;241m=[39m [43mmx2[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mCTi2[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mvacuum[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;241;43m15[39;49m[43m)[49m

File [0;32m~/.local/lib/python3.10/site-packages/ase/build/surface.py:502[0m, in [0;36mmx2[0;34m(formula, kind, a, thickness, size, vacuum)[0m
[1;32m    500[0m [38;5;28;01mif[39;00m vacuum [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    501[0m     atoms[38;5;241m.[39mcenter(vacuum, axis[38;5;241m=[39m[38;5;241m2[39m)
[0;32m--> 502[0m atoms [38;5;241m=[39m [43matoms[49m[38;5;241;43m.[39;49m[43mrepeat[49m[43m([49m[43msize[49m[43m)[49m
[1;32m    503[0m [38;5;28;01mreturn[39;00m atoms

File [0;32m~/.local/lib/python3.10/site-packages/ase/atoms.py:1205[0m, in [0;36mAtoms.repeat[0;34m(self, rep)[0m
[1;32m   1198[0m [38;5;250m[39m[38;5;124;03m"""Create new repeated atoms object.[39;00m
[1;32m   1199[0m 
[1;32m   1200[0m [38;5;124;03mThe *rep* argument should be a sequence of three positive[39;00m
[1;32m   1201[0m [38;5;124;03mintegers like *(2,3,1)* or a single integer (*r*) equivalent[39;00m
[1;32m   1202[0m [38;5;124;03mto *(r,r,r)*."""[39;00m
[1;32m   1204[0m atoms [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcopy()
[0;32m-> 1205[0m atoms [38;5;241m*[39m[38;5;241m=[39m rep
[1;32m   1206[0m [38;5;28;01mreturn[39;00m atoms

File [0;32m~/.local/lib/python3.10/site-packages/ase/atoms.py:1175[0m, in [0;36mAtoms.__imul__[0;34m(self, m)[0m
[1;32m   1171[0m     [38;5;28;01mif[39;00m x [38;5;241m!=[39m [38;5;241m1[39m [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m vec[38;5;241m.[39many():
[1;32m   1172[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m'[39m[38;5;124mCannot repeat along undefined lattice [39m[38;5;124m'[39m
[1;32m   1173[0m                          [38;5;124m'[39m[38;5;124mvector[39m[38;5;124m'[39m)
[0;32m-> 1175[0m M [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mproduct[49m(m)
[1;32m   1176[0m n [38;5;241m=[39m [38;5;28mlen[39m([38;5;28mself[39m)
[1;32m   1178[0m [38;5;28;01mfor[39;00m name, a [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39marrays[38;5;241m.[39mitems():

File [0;32m~/.local/lib/python3.10/site-packages/numpy/__init__.py:414[0m, in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    411[0m     [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mnumpy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mchar[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mchar[39;00m
[1;32m    412[0m     [38;5;28;01mreturn[39;00m char[38;5;241m.[39mchararray
[0;32m--> 414[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124m"[39m[38;5;124mmodule [39m[38;5;132;01m{!r}[39;00m[38;5;124m has no attribute [39m[38;5;124m"[39m
[1;32m    415[0m                      [38;5;124m"[39m[38;5;132;01m{!r}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat([38;5;18m__name__[39m, attr))

[0;31mAttributeError[0m: module 'numpy' has no attribute 'product'

