Traceback (most recent call last):
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ase.build import bulk
from ase.visualize import view

atoms = bulk('C','diamond', 3.57)

view(atoms, backend='x3d')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 6[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mase[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvisualize[39;00m [38;5;28;01mimport[39;00m view
[1;32m      4[0m atoms [38;5;241m=[39m bulk([38;5;124m'[39m[38;5;124mC[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mdiamond[39m[38;5;124m'[39m, [38;5;241m3.57[39m)
[0;32m----> 6[0m [43mview[49m[43m([49m[43matoms[49m[43m,[49m[43m [49m[43mbackend[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mx3d[39;49m[38;5;124;43m'[39;49m[43m)[49m

[0;31mTypeError[0m: view() got an unexpected keyword argument 'backend'

