Traceback (most recent call last):
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.tree import DecisionTreeClassifier()

# fit a decision tree model to the data: 
dtree = DecisionTreeClassifier(max_depth=10)
dtree.fit(z_train, y_train)

# evaluate the model on the training and validation set:
train_accuracy = dtree.score(z_train, y_train)
val_accuracy = dtree.score(z_val, y_val)

# print the accuracy of the model:
print('training set accuracy:  ', train_accuracy)
print('validation set accuracy:', val_accuracy)
------------------


[0;36m  Cell [0;32mIn[12], line 1[0;36m[0m
[0;31m    from sklearn.tree import DecisionTreeClassifier()[0m
[0m                                                   ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


