Traceback (most recent call last):
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
n = 50

f_prev = 0
f_current = 1

for i in range(n):
    f_next = f_prev + f_current
    f_prev = f_current
    f_current  = f_next

phi = f_current / f_prev

print('F(n):', f_current)
prunt('F(n)/F(n-1):', phi)
------------------

----- stdout -----
F(n): 20365011074
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 14[0m
[1;32m     11[0m phi [38;5;241m=[39m f_current [38;5;241m/[39m f_prev
[1;32m     13[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mF(n):[39m[38;5;124m'[39m, f_current)
[0;32m---> 14[0m [43mprunt[49m([38;5;124m'[39m[38;5;124mF(n)/F(n-1):[39m[38;5;124m'[39m, phi)

[0;31mNameError[0m: name 'prunt' is not defined

