Traceback (most recent call last):
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# print the type of string (str) objects:
print(type('Hello World')
print(type('This is some text')
print(type('')) # <-- '' is the empty string

# print the type of integer (int) objects:
print(type(42))         # 42
print(type(1 - 7))      # -6
print(type(3 * 13))     # 39

# print the type of floating-point (float) objects:
print(type(2 * 10**-9)) # 2.0e-9 
print(type(1.0))        # 1.0 (!)
print(type(42 / 6))     # 7.0 (!)
print(type(16**(-2)))   # 4.0 (!)
------------------


[0;36m  Cell [0;32mIn[7], line 3[0;36m[0m
[0;31m    print(type('This is some text')[0m
[0m         ^[0m
[0;31mSyntaxError[0m[0;31m:[0m '(' was never closed


